//! Deterministic model-based state-machine tests for the GCRA implementation.
//!
//! A simple reference model of GCRA (a handful of lines of integer
//! arithmetic) is checked against the library's direct and keyed
//! limiters, operation by operation. The operation sequences cover
//! time advancing, time rewinding, single cells, legal batches,
//! batches exceeding the burst size, exact arrivals at the announced
//! retry instant, and keyed `retain_recent` cleanup.
//!
//! Every step compares:
//!   * whether the cell(s) are admitted,
//!   * the earliest possible retry time reported on rejection,
//!   * the subsequent limiter state (remaining burst capacity, live keys).
//!
//! Sequences are generated by a fixed-seed PRNG, so the whole run is
//! deterministic. On a mismatch, the failing sequence is greedily
//! minimized and the shortest still-failing sequence is printed.
#![cfg(feature = "std")]

mod common;

use common::RewindableClock;
use governor::middleware::{StateInformationMiddleware, StateSnapshot};
use governor::nanos::Nanos;
use governor::state::keyed::HashMapStateStore;
use governor::state::{InMemoryState, NotKeyed};
use governor::{InsufficientCapacity, NotUntil, Quota, RateLimiter};
use std::collections::BTreeMap;
use std::num::NonZeroU32;
use std::time::Duration;

/// The quota under test: one cell every 500ms, burst of 4.
const CELL_NS: u64 = 500_000_000;
const BURST: u32 = 4;
const TAU_NS: u64 = CELL_NS * (BURST as u64 - 1);

fn quota() -> Quota {
    Quota::per_second(NonZeroU32::new(2).unwrap()).allow_burst(NonZeroU32::new(BURST).unwrap())
}

/// Advance amounts (ns) biased towards interesting GCRA boundaries.
const ADVANCE_AMOUNTS: &[u64] = &[
    1,
    CELL_NS / 2,
    CELL_NS - 1,
    CELL_NS,
    CELL_NS + 1,
    2 * CELL_NS,
    TAU_NS,
    TAU_NS + CELL_NS,
    4 * CELL_NS,
    20 * CELL_NS,
];
const REWIND_AMOUNTS: &[u64] = &[1, CELL_NS / 2, CELL_NS, 2 * CELL_NS, 5 * CELL_NS];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Target {
    Direct,
    Keyed(u32),
}

#[derive(Debug, Clone, Copy)]
enum Op {
    /// Move the clock forward.
    Advance(u64),
    /// Move the clock backwards (saturating at 0).
    Rewind(u64),
    /// Check a single cell.
    CheckOne(Target),
    /// Check a legal batch of `n <= BURST` cells.
    CheckN(Target, u32),
    /// Check a batch larger than the burst size (never conforming).
    CheckTooMany(Target),
    /// Advance exactly to the model's announced retry instant (if
    /// currently rejected), then check a single cell. Arriving at
    /// exactly the announced instant must conform.
    CheckExactRetry(Target),
    /// Run keyed-limit housekeeping.
    RetainRecent,
}

// ---------------------------------------------------------------------------
// Reference model
// ---------------------------------------------------------------------------

/// The theoretical arrival time state of one bucket, in ns since limiter start.
type Tat = Option<u64>;

#[derive(Debug, Default)]
struct Model {
    now: u64,
    direct_tat: Tat,
    /// Key presence mirrors the state store: an entry exists once a key
    /// was touched by a (conforming or non-conforming) single/batch check.
    keyed: BTreeMap<u32, Tat>,
}

/// Remaining burst capacity after a positive decision, mirroring
/// [`StateSnapshot::remaining_burst_capacity`].
fn model_remaining(t0: u64, new_tat: u64) -> u32 {
    (std::cmp::min(
        (t0 + TAU_NS + CELL_NS).saturating_sub(new_tat),
        TAU_NS + CELL_NS,
    ) / CELL_NS) as u32
}

/// One GCRA decision for `n` cells against `slot`.
///
/// Returns `Ok(remaining_burst_capacity)` on a positive decision and
/// `Err(earliest_retry_instant)` on a negative one. Negative decisions
/// never mutate the state.
fn model_check(slot: &mut Tat, now: u64, n: u32) -> Result<u32, u64> {
    let tat = slot.unwrap_or(now);
    let additional = CELL_NS * (n as u64 - 1);
    let earliest = (tat + additional).saturating_sub(TAU_NS);
    if now < earliest {
        Err(earliest)
    } else {
        let next = tat.max(now) + CELL_NS + additional;
        *slot = Some(next);
        Ok(model_remaining(now, next))
    }
}

impl Model {
    fn check(&mut self, target: Target, n: u32) -> Result<u32, u64> {
        let now = self.now;
        let slot = match target {
            Target::Direct => &mut self.direct_tat,
            Target::Keyed(key) => self.keyed.entry(key).or_insert(None),
        };
        model_check(slot, now, n)
    }

    fn tat_of(&self, target: Target) -> Tat {
        match target {
            Target::Direct => self.direct_tat,
            Target::Keyed(key) => self.keyed.get(&key).copied().flatten(),
        }
    }
}

// ---------------------------------------------------------------------------
// Harness: run one operation against model + both limiters and compare
// ---------------------------------------------------------------------------

type DirectLim = RateLimiter<NotKeyed, InMemoryState, RewindableClock, StateInformationMiddleware>;
type KeyedLim =
    RateLimiter<u32, HashMapStateStore<u32>, RewindableClock, StateInformationMiddleware>;

struct Harness {
    clock: RewindableClock,
    direct: DirectLim,
    keyed: KeyedLim,
    model: Model,
}

impl Harness {
    fn new() -> Self {
        let clock = RewindableClock::default();
        let direct = RateLimiter::direct_with_clock(quota(), clock.clone())
            .with_middleware::<StateInformationMiddleware>();
        let keyed = RateLimiter::hashmap_with_clock(quota(), clock.clone())
            .with_middleware::<StateInformationMiddleware>();
        Harness {
            clock,
            direct,
            keyed,
            model: Model::default(),
        }
    }

    fn compare(
        ctx: &str,
        now: u64,
        model: Result<u32, u64>,
        actual: Result<StateSnapshot, NotUntil<Nanos>>,
    ) -> Result<(), String> {
        match (model, actual) {
            (Ok(model_rem), Ok(snapshot)) => {
                let actual_rem = snapshot.remaining_burst_capacity();
                if model_rem != actual_rem {
                    return Err(format!(
                        "{ctx}: admitted with remaining capacity {actual_rem}, model says {model_rem}"
                    ));
                }
                Ok(())
            }
            (Err(retry), Err(not_until)) => {
                let actual_retry = not_until.earliest_possible().as_u64();
                if actual_retry != retry {
                    return Err(format!(
                        "{ctx}: rejected with earliest retry at {actual_retry}ns, model says {retry}ns"
                    ));
                }
                let wait = not_until.wait_time_from(Nanos::from(now));
                let model_wait = Duration::from_nanos(retry - now);
                if wait != model_wait {
                    return Err(format!(
                        "{ctx}: rejected with wait {wait:?}, model says {model_wait:?}"
                    ));
                }
                Ok(())
            }
            (Ok(rem), Err(not_until)) => Err(format!(
                "{ctx}: limiter rejected (retry at {}ns) but model admits (remaining {rem})",
                not_until.earliest_possible().as_u64()
            )),
            (Err(retry), Ok(_)) => Err(format!(
                "{ctx}: limiter admitted but model rejects until {retry}ns"
            )),
        }
    }

    fn check_one(&mut self, ctx: &str, target: Target) -> Result<(), String> {
        let now = self.model.now;
        let model = self.model.check(target, 1);
        let actual = match target {
            Target::Direct => self.direct.check(),
            Target::Keyed(key) => self.keyed.check_key(&key),
        };
        Self::compare(ctx, now, model, actual)
    }

    fn step(&mut self, index: usize, op: &Op) -> Result<(), String> {
        let ctx = format!("op #{index} {op:?} at t={}ns", self.model.now);
        match *op {
            Op::Advance(delta) => {
                self.model.now += delta;
                self.clock.advance(Duration::from_nanos(delta));
            }
            Op::Rewind(delta) => {
                self.model.now = self.model.now.saturating_sub(delta);
                self.clock.rewind(Duration::from_nanos(delta));
            }
            Op::CheckOne(target) => self.check_one(&ctx, target)?,
            Op::CheckN(target, n) => {
                let now = self.model.now;
                let model = self.model.check(target, n);
                let nz = NonZeroU32::new(n).unwrap();
                let actual = match target {
                    Target::Direct => self.direct.check_n(nz),
                    Target::Keyed(key) => self.keyed.check_key_n(&key, nz),
                };
                let actual = match actual {
                    Ok(outcome) => outcome,
                    Err(cap) => {
                        return Err(format!(
                            "{ctx}: unexpected InsufficientCapacity({}) for legal batch n={n}",
                            cap.0
                        ))
                    }
                };
                Self::compare(&ctx, now, model, actual)?;
            }
            Op::CheckTooMany(target) => {
                let nz = NonZeroU32::new(BURST + 1).unwrap();
                let actual = match target {
                    Target::Direct => self.direct.check_n(nz),
                    Target::Keyed(key) => self.keyed.check_key_n(&key, nz),
                };
                match actual {
                    Err(cap) if cap == InsufficientCapacity(BURST) => {}
                    other => {
                        return Err(format!(
                            "{ctx}: expected InsufficientCapacity({BURST}), got {other:?}"
                        ))
                    }
                }
                // An over-capacity batch must not touch any state:
                let (actual, expected) = (self.keyed.len(), self.model.keyed.len());
                if actual != expected {
                    return Err(format!(
                        "{ctx}: over-capacity batch mutated the store ({actual} live keys, model has {expected})"
                    ));
                }
            }
            Op::CheckExactRetry(target) => {
                if let Some(tat) = self.model.tat_of(target) {
                    let earliest = tat.saturating_sub(TAU_NS);
                    if self.model.now < earliest {
                        let wait = earliest - self.model.now;
                        self.model.now = earliest;
                        self.clock.advance(Duration::from_nanos(wait));
                    }
                }
                self.check_one(&ctx, target)?;
            }
            Op::RetainRecent => {
                let drop_below = self.model.now.saturating_sub(CELL_NS);
                self.model
                    .keyed
                    .retain(|_, tat| tat.unwrap_or(0) > drop_below);
                self.keyed.retain_recent();
                let (actual, expected) = (self.keyed.len(), self.model.keyed.len());
                if actual != expected {
                    return Err(format!(
                        "{ctx}: retain_recent left {actual} live keys, model expects {expected}"
                    ));
                }
            }
        }
        Ok(())
    }
}

fn run(ops: &[Op]) -> Result<Model, String> {
    let mut harness = Harness::new();
    for (index, op) in ops.iter().enumerate() {
        harness
            .step(index, op)
            .map_err(|err| format!("{err}\n  model state: {:?}", harness.model))?;
    }
    Ok(harness.model)
}

// ---------------------------------------------------------------------------
// Deterministic sequence generation + greedy minimization
// ---------------------------------------------------------------------------

/// A tiny xorshift64* PRNG: deterministic across platforms and runs.
struct Rng(u64);

impl Rng {
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }
}

fn gen_ops(seed: u64, len: usize) -> Vec<Op> {
    let mut rng = Rng(seed);
    (0..len)
        .map(|_| {
            let target = if rng.below(4) == 0 {
                Target::Direct
            } else {
                Target::Keyed(rng.below(3) as u32)
            };
            match rng.below(12) {
                0 | 1 => {
                    Op::Advance(ADVANCE_AMOUNTS[rng.below(ADVANCE_AMOUNTS.len() as u64) as usize])
                }
                2 => Op::Rewind(REWIND_AMOUNTS[rng.below(REWIND_AMOUNTS.len() as u64) as usize]),
                3..=6 => Op::CheckOne(target),
                7 | 8 => Op::CheckN(target, 1 + rng.below(BURST as u64) as u32),
                9 => Op::CheckTooMany(target),
                10 => Op::CheckExactRetry(target),
                _ => Op::RetainRecent,
            }
        })
        .collect()
}

/// Greedily removes operations while the sequence still fails,
/// yielding a (locally) minimal reproducing sequence.
fn shrink(ops: &[Op]) -> Vec<Op> {
    let mut ops = ops.to_vec();
    let mut i = 0;
    while i < ops.len() {
        let mut candidate = ops.clone();
        candidate.remove(i);
        if run(&candidate).is_err() {
            ops = candidate;
        } else {
            i += 1;
        }
    }
    ops
}

#[test]
fn model_based_state_machine_matches_direct_and_keyed_limiters() {
    for seed in 0..400u64 {
        let ops = gen_ops(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1, 48);
        if let Err(err) = run(&ops) {
            let minimal = shrink(&ops);
            panic!(
                "limiter diverged from reference model (seed {seed}):\n{err}\n\n\
                 shortest reproducing sequence ({} ops):\n{minimal:#?}",
                minimal.len()
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Hand-written regression sequences pinning down specific mutation classes
// ---------------------------------------------------------------------------

/// Arriving at *exactly* the announced retry instant must conform.
/// Catches `t0 < earliest` being written as `t0 <= earliest`.
#[test]
fn regression_arrival_exactly_at_earliest_retry_conforms() {
    run(&[
        Op::CheckN(Target::Direct, BURST),   // exhaust the bucket
        Op::CheckOne(Target::Direct),        // rejected
        Op::CheckExactRetry(Target::Direct), // lands exactly on the retry instant
        Op::CheckOne(Target::Direct),        // rejected again right after
    ])
    .unwrap();
}

/// A batch check is atomic: a rejected batch must not partially consume
/// capacity (as it would if implemented as repeated single-cell checks).
#[test]
fn regression_batch_is_atomic_not_repeated_single_checks() {
    run(&[
        Op::CheckN(Target::Direct, 3), // tat = 1.5s
        Op::CheckN(Target::Direct, 2), // rejected until 0.5s; state must stay at 1.5s
        Op::Advance(CELL_NS / 2),      // t = 0.5s
        Op::CheckOne(Target::Direct),  // admitted, tat = 2.0s
        Op::CheckOne(Target::Direct),  // admitted exactly at the boundary
        Op::CheckOne(Target::Direct),  // rejected
    ])
    .unwrap();
}

/// `retain_recent` must only evict stale keys and leave other keys'
/// rate-limiting state fully intact.
#[test]
fn regression_retain_recent_preserves_sibling_keys() {
    run(&[
        Op::CheckOne(Target::Keyed(0)), // key 0: tat = 0.5s
        Op::Advance(4 * CELL_NS),       // t = 2s
        Op::CheckOne(Target::Keyed(1)),
        Op::CheckOne(Target::Keyed(1)), // key 1: tat = 3.0s
        Op::RetainRecent,               // evicts key 0 (stale), keeps key 1
        Op::CheckOne(Target::Keyed(1)), // key 1's remaining capacity reflects its kept state
        Op::CheckOne(Target::Keyed(0)), // key 0 is fresh again: full burst available
        Op::CheckOne(Target::Keyed(0)),
        Op::CheckOne(Target::Keyed(0)),
        Op::CheckOne(Target::Keyed(0)),
        Op::CheckOne(Target::Keyed(0)), // 5th cell on fresh key: rejected
    ])
    .unwrap();
}

/// A rewound clock must not resurrect spent capacity nor corrupt state.
#[test]
fn regression_rewound_clock_behaves() {
    run(&[
        Op::Advance(8 * CELL_NS),
        Op::CheckN(Target::Direct, BURST),
        Op::Rewind(2 * CELL_NS), // clock jumps backwards
        Op::CheckOne(Target::Direct),
        Op::CheckExactRetry(Target::Direct),
        Op::Rewind(100 * CELL_NS), // rewinding below the start saturates at 0
        Op::CheckOne(Target::Keyed(1)),
        Op::CheckOne(Target::Direct),
    ])
    .unwrap();
}
